### ISSUE TITLE
Raspberry Pi logo fails

### ISSUE THREAD

**Issue by thomaskole** [sameer/svg2gcode#10]
I love this project, it's so much faster than any Python implementation I've found.
It even runs on my Raspberry Pi!

I'm trying to create a simple wooden board holding that same Pi, but I noticed it fails on the logo.
The middle berry parts turn into triangle. There's no warnings that I can see.

I've attached the SVG so you can try for yourself.

[out.gcode.zip](https://github.com/sameer/svg2gcode/files/6610402/out.gcode.zip)
[board_attachment.svg.zip](https://github.com/sameer/svg2gcode/files/6610409/board_attachment.svg.zip)
![image](https://user-images.githubusercontent.com/29757178/121051192-8b026800-c7b9-11eb-91c2-40e01b80d29b.png)

**Comment by thomaskole** [comment]
Also, it seems to go over the circles multiple times, even though they are just regular closed paths.

**Comment by sameer** [comment]
> I love this project, it's so much faster than any Python implementation I've found.
It even runs on my Raspberry Pi!

Haha that's nice to hear :slightly_smiling_face: I had some plans to compile this to WASM and host it for people who aren't familiar with/don't care for the toolchain setup but haven't gotten around to it yet.

Thanks for bringing these issues to my attention, I'll take a look

**Comment by sameer** [comment]
Ok, I think I have a good idea of what's going on. Like with a couple of other similar issues, this ties back to the difference between SVG and GCode coordinate systems and how I've translated things.

**Comment by sameer** [comment]
I've fixed the first issue with ellipses called out in 2c52f3bc8716bdd51b0191e47002b994edd4d7aa.

![image](https://user-images.githubusercontent.com/11097096/121109730-1d1a6880-c7da-11eb-8235-0de6f2cf5b5f.png)

Two problems and solutions here:

1. There is a bug in lyon_geom itself: the G1 moves produced by flattening the curve w/ a tolerance do not work *at all* with a negative sweep angle (see [flattening_step](https://docs.rs/lyon_geom/0.17.1/src/lyon_geom/arc.rs.html#330)). There are no tests for that method either which might explain how it has gone unnoticed for so long.
   * Solution: roundabout method where we can convert the ellipse is converted to cubic bezier segments, then flattened that into line segments.
2. There is some ambiguity around large-arc, sweep, and radii when moving between SVG and GCode coordinate systems. I ran into this previously and had a temporary fix of just inverting large-arc which worked at the time for my use case, but not everywhere.
    * Solution: For simplicity's sake just transform all the points that come out of the flattening. Not as performant but can revisit the math around swapping coordinate systems for elliptical arcs later.

**Comment by sameer** [comment]
As for the second issue, I will check if it's still happening and create a separate tracking issue.

**Comment by sameer** [comment]
Other issue doesn't seem to manifest. Now that I think about it those were probably also ellipses...so the solution is the same

**Comment by thomaskole** [comment]
Awesome, I'll check out the fix!

**Comment by sameer** [comment]
follow up from the dependency issue: that is now resolved by nical/lyon#662 and I've reverted the roundabout solution 1 in e9b23c1
