### ISSUE TITLE
Support biarc interpolation

### ISSUE THREAD

**Issue by sameer** [sameer/svg2gcode#12]
Biarc interpolation means GCode can consist of a few G2/G3 moves instead of many G1 moves. This will reduce gcode output size and improve handling of tolerances, assuming the machine better understands its own constraints and how to achieve the desired quality.

It should only be enabled when a flag is specified as many older/simpler machines do not support them.

**Comment by LeLocTai** [comment]
https://github.com/FormerLurker/ArcWelderLib worked very well for me for 3d printing. There even are prebuilt libraries.

**Comment by sameer** [comment]
Interesting, thanks for sharing that. It may be worth contributing any improvements here upstream to lyon_geom.
