### ISSUE TITLE
Allow export/import settings for web UI

### ISSUE THREAD

**Issue by matopeto** [sameer/svg2gcode#22]
Would be nice to have ability to export custom settings from web UI and import to other machine

**Comment by sameer** [comment]
Hey matopeto,

Just pushed changes to add support for this. Let me know what you think!

![image](https://user-images.githubusercontent.com/11097096/139609091-8074f40f-a894-40e9-8078-d611a5ea4ace.png)

![image](https://user-images.githubusercontent.com/11097096/139609105-ee200822-9747-4d72-b11b-b14458441b6f.png)

**Comment by matopeto** [comment]
Hi @sameer, it looks great

Thanks for keeping my old unsuported pen plotter alive :)

But maybe two little UX things (sorry i don't want to be annoying) but
1. from button "Import/Export" isn't (for me) clear what will be imported/exported before i click on it
 - Maybe renaming to "Import/Export Settings" would be better 
 - Or move the button to the settings window on the top
 
 2. Is there any documentation how to use the json in the CLI?

**Comment by sameer** [comment]
Those are both good points, I think moving the import/export button to be in the settings window would make sense.

I have been meaning to add docs for CLI in a wiki page but haven't gotten around to it. It is pretty straightforward

```
# To import settings
svg2gcode --setings svg2gcode_settings.json input.svg -o output.gcode
# Arguments will override any imported settings (i.e. if circular interpolation is false in config, you can override that to true via a CLI arg)
svg2gcode --setings svg2gcode_settings.json --circular-interpolation true input.svg -o output.gcode
# To export settings (circular interpolation + feedrate)
svg2gcode --circular-interpolation true --feedrate 300 --export svg2gcode_settings.json
```
