### ISSUE TITLE
Program End Sequence is not exactly same in exported GCODE

### ISSUE THREAD

**Issue by matopeto** [sameer/svg2gcode#23]
I am using web interface

I set "Program End Sequence" to 

```
M05 S0
G1 F3500
G1 X0 Y0
M30
```

but it generates:

```
M5 S0
G1 F3500
G1 X0 Y0.0000009999999974752427
M30
M2
```

It is practicaly the same, but i expect to be exactly same as i write to the settings

**Comment by sameer** [comment]
Hi matopeto,

Sharing an update after I looked into this further. It is related to svg2gcode's origin option which is applied in a post-processing step after the g-code is generated.

For your first SVG, the code without any post-processing would've been:
```gcode
G21
G90;svg#svg8 > g#layer1 > path#path3680
G0 X0.11936799641895846 Y-0.0000009999999974752427
G1 X0.11936799641895668 Y100.00000000000003 F300;svg#svg8 > g#layer1 > path#path3682
G0 X99.88062200358111 Y98.67549498675496
G1 X99.88062200358111 Y52.31787952317879 F300
G1 X55.62035533138921 Y52.3178795231788 F300
G1 X0 Y0
M2
```
The first G0 move would go negative. This is avoided by translating all the move commands. And that happens to include any inserted custom g-code sequences like program end.

The same issue occurs with your second SVG.


This behavior feels a bit unintuitive, you would expect the sequence to be identical in the output. I am thinking of chaning origin handling to only apply to the SVG (no postprocessing step). What do you think?

**Comment by matopeto** [comment]
> This behavior feels a bit unintuitive, you would expect the sequence to be identical in the output. I am thinking of chaning origin handling to only apply to the SVG (no postprocessing step). What do you think?

Hm.. this is very ineresting. Thanks for explenation.

I am thinking that posprocessing should be applyed only to SVG only not begin/end sequences, because (I think) that is very good to some before and after steps independend of the SVG. E.g. in my case pen up and return to the zero/home position. But don't know how this change will affect other users using your program. But for me it would be expected behaviour.

**Comment by sameer** [comment]
Hey matopeto,

I've pushed some changes which should resolve this and confirmed they work with your SVG. Let me know if you run into any other problems!

**Comment by matopeto** [comment]
@sameer thank you :)
