### ISSUE TITLE
Support other non-closed, non-path elements

### ISSUE THREAD

**Issue by sameer** [sameer/svg2gcode#38]
#32 pointed out that polylines don't work. Line should also work https://www.w3.org/TR/SVG11/shapes.html#LineElement

**Comment by kvdveer** [comment]
I've started work on this, I've written the code for `rect`, `circle`, `ellipse`, `line`, and `polyline`. I believe those are all the shapes from the spec.

Unfortunately I'm running into some problems with the coordinate system, I'm afraid I'll have to rework some of that according to [SVG1.1 § 7](https://www.w3.org/TR/SVG11/coords.html). Do you prefer the coordinate rework as a separate MR, or as part of this one?

**Comment by sameer** [comment]
1 is fine, I appreciate you looking into this!

**Comment by sameer** [comment]
Fixed by 225574d34a7a180a68cac443711671845966149a
