### ISSUE TITLE
Button disabled

### ISSUE THREAD

**Issue by tools-for-things-and-ideas** [sameer/svg2gcode#50]
Hello Sameer, 

I've been using the svg2gcode website a while. It's great!
But today the 'Generate G-code' stays greyed out (disabled). I tested this on multible browsers and computers (macs).
My apologies if I'm doing something wrong here.

All the best,
Elias Heuninck
http://www.formlab.schoolofarts.be/

**Comment by sameer** [comment]
Weird, I think the latest release must've gone wrong. I'll look into this, thanks for letting me know!

**Comment by sameer** [comment]
Haven't figured out what's wrong but I have reverted the relevant change, this should be fixed in a few minutes

**Comment by tools-for-things-and-ideas** [comment]
Thank you so much Sameer!

**Comment by sameer** [comment]
The issue that caused this is fixed by 47e0301908494ca1f96f188e3cbd1bcfdbf25df8.
