### ISSUE TITLE
DTD Detected

### ISSUE THREAD

**Issue by coycash** [sameer/svg2gcode#54]
If I run svg2gcode.exe and leave this line in my svg:

`<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">`

I get the error:

thread 'main' panicked at cli/src/main.rs:271:55:
called `Result::unwrap()` on an `Err` value: DtdDetected
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

If I remove the line it runs fine.

**Comment by sameer** [comment]
Hi @coycash, thanks for creating this issue. I've fixed it in v0.0.9: https://github.com/sameer/svg2gcode/releases/tag/cli-v0.0.9
